if(input.Type_field == "Boat")
    {
        boatValue = {"Boat Substitution","Add Auxillary Engine","Add Tender","Add Boat Trailer","Add Boat","Boat Addition","Change Principal Operator","Cancellation Request"};
        input.Change_Request_Type:ui.add(boatValue);
        coveragesValue = {"Replacement Cost (MSRP + Taxes)","Actual Cash Value"};
        input.Coverages:ui.add(coveragesValue);
        //	input.Change_Request_Type = "Boat Substitution";
    }
    else if(input.Type_field == "Trailer")
    {
        trailerValue = {"Trailer Substitution","Add Golf Cart","Amend Risk Location","Amend Mailing Location","Trailer Addition","Add Snow Bird","Cancellation Request"};
        input.Change_Request_Type:ui.add(trailerValue);
        coveragesTrailerValue = {"Replacement Cost","Actual Cash Value"};
        input.Coverages:ui.add(coveragesTrailerValue);
    }
    if(input.Change_Request_Type == null)
    {
        hide Effective_Date;
        hide Spoke_with;
        hide Update_Phone;
        hide Update_Email;
        hide Confirmed_Email_Phone;
        hide Confirmed_Client;
        hide X_Sell;
        hide Highlights_Comments;
        hide What_Iam_Waiting_for;
        hide Lien_Holder_Address;
        hide Lien_Holder_Name;
        hide Business_Rental_Exposure;
        hide Trailer_Coming_off_Reason;
        hide Where_was_the_new_trailer_purchased_from;
        hide New_Trailers_Year;
        hide New_Trailers_Manufacturer;
        hide New_Trailers_Model;
        hide Trailer_Type;
        hide Trailer_width;
        hide VIN;
        hide Less_than_90_days_US_Expoure;
        hide Value;
        hide Coverages;
        hide Is_your_trailer_financed;
        hide Is_this_trailer_permanently_parked;
        hide Park_Name;
        hide Park_Address;
        hide Site_Number;
        hide Add_a_room_Length;
        hide Add_a_room_Width;
        hide Add_a_golf_Cart;
        hide Golf_Cart_Value;
        hide Is_the_site_within_500ft_of_a_body_of_water;
        hide Eligible_for_WPP;
        hide Do_you_have_a_screened_in_room_or_a_Florida_room;
        hide Screened_in_room_Florida_room_length;
        hide Screened_in_room_Florida_room_width;
        hide Deck_Width_Ft;
        hide Deck_Length_Ft;
        hide Deck_y_n;
        hide New_Mailing_Address;
        hide Confirmed_Trailer_address;
        hide Hard_Awning_Length;
        hide Hard_Awning_Width;
        hide Boat_coming_off_reason;
        hide Where_was_the_new_boat_purchased_from;
        hide Boat_type;
        hide New_Boats_Year;
        hide Boat_Make;
        hide Boat_Model;
        hide Total_Value_boat_motor_s_trailer_tender_inclusive_of_tax;
        hide What_province_is_the_boat_used_in;
        hide Has_the_PO_of_the_boat_changed_Y_N;
        hide Principal_Operator_First_Name;
        hide Principal_Operator_Last_Name;
        hide Principal_Operator_Date_of_Birth;
        hide Principal_operator_s_years_of_boating_experience_with_vessels_of_a_similar_size_and_type;
        hide Does_the_operator_hold_a_Pleasure_Craft_Operators_Card_PCOC;
        hide Usage_of_boat_changed_Y_N;
        hide Boat_Length;
        hide Hull_ID_Serial;
        hide Hull_Type;
        hide Max_speed_MPH;
        hide Main_engine_type;
        hide Fuel_Type;
        hide Engine_model_year;
        hide Engine_manufacturer;
        hide Engine_serial;
        hide HP;
        hide Add_a_boat_trailer_Y_N;
        hide Add_a_tender_Y_N;
        hide Add_an_auxiliary_motor_Y_N;
        hide Is_your_boat_financed;
        hide Aux_Engine_Model_Year;
        hide Aux_Engine_Value;
        hide Aux_Engine_Manufacturer;
        hide Aux_Engine_HP_Thrust;
        hide Aux_engine_type;
        hide Aux_engine_fuel_type;
        hide Auxiliary_Engine_Serial;
        hide New_value_insured_for_boat_motor_s_trailer_tender_inclusive_of_tax;
        hide Tender_Value;
        hide Tender_Model_Year;
        hide Tender_Manufacturer;
        hide Trailer_VIN;
        hide Tender_Length;
        hide Trailer_Value;
        hide Trailer_Model_Year;
        hide Trailer_Manufacturer;
        hide Country;
        hide Address;
        hide Suite_Apt;
        hide City;
        hide Province;
        hide Postal_code_ZIP_Code;
        hide Confirm_province_boat_is_used_in;
        hide Reason_For_Cancellation;
        hide Deductible;
        hide Personal_Effects;
        hide Navigational_Equipment;
        hide Trailer_Length;
        hide Do_you_live_in_the_trailer_full_time_all_year_round_as_a_principal_residence;
        hide Add_Snowbird_Endorsement;
        hide Non_Domestic_Address;
        hide New_Trailer_Address;
        hide New_Trailer_Make;
        hide Tender_Serial;
        hide Cancellation_Date;
        hide Carrier;
        hide Expiry_Date;
        hide Tender_Value;
    }
    